# Generated by Django 3.2 on 2023-01-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default='ptKbiPgTir3wEjKWDti1zUKnoOQTnEO7', editable=False, max_length=32, unique=True, verbose_name='API key')),
                ('aruco', models.IntegerField(unique=True, verbose_name='Aruco ID')),
                ('opened', models.BooleanField(default=False, editable=False, verbose_name='Is station open')),
                ('done', models.BooleanField(default=False, editable=False, verbose_name='Is work done')),
            ],
        ),
    ]
