# Generated by Django 3.2 on 2023-01-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='api_key',
        ),
    ]
