# Generated by Django 3.2 on 2023-01-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_station_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='api_key',
            field=models.CharField(default=234, help_text='<script>function genRand = (len) => {document.getElementById("id_api_key").textContent = Math.random().toString(36).substring(2,len+2);}</script>', max_length=32, unique=True, verbose_name='API Key'),
            preserve_default=False,
        ),
    ]
