# Generated by Django 3.2 on 2023-01-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230110_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вашего вопроса')),
                ('contact', models.CharField(max_length=128, verbose_name='Как с вами связаться')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('rewiewed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
        ),
    ]
