# Generated by Django 3.2 on 2023-01-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
