# Generated by Django 3.2 on 2023-01-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_questions_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='<a onclick="genRand()">Generate new random key</a><script>function genRand() {var result = "INSECURE-";for (var i = 1; i < 21; i++) {result += "abcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(Math.random() * 36));if (i % 5 == 0 && i != 20) result += "-"}document.getElementById("id_api_key").value = result;}if (!document.getElementById("id_api_key").value) genRand()</script>', max_length=32, unique=True, verbose_name='API Key')),
                ('disabled', models.BooleanField(default=False, verbose_name='Disabled')),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='api_key',
            field=models.CharField(help_text='<a onclick="genRand()">Generate new random key</a><script>function genRand() {var result = "INSECURE-";for (var i = 1; i < 21; i++) {result += "abcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(Math.random() * 36));if (i % 5 == 0 && i != 20) result += "-"}document.getElementById("id_api_key").value = result;}if (!document.getElementById("id_api_key").value) genRand()</script>', max_length=32, unique=True, verbose_name='API Key'),
        ),
    ]
