# Generated by Django 3.2 on 2023-01-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230111_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'зарядная станция', 'verbose_name_plural': 'зарядные станции'},
        ),
        migrations.RemoveField(
            model_name='flight',
            name='disabled',
        ),
        migrations.AlterField(
            model_name='question',
            name='contact',
            field=models.CharField(max_length=128, verbose_name='Обратная связь'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='station',
            name='disabled',
            field=models.BooleanField(default=False, editable=False, verbose_name='Busy'),
        ),
    ]
