# Generated by Django 3.2 on 2023-05-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230111_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'дрон', 'verbose_name_plural': 'дроны'},
        ),
    ]
